/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_weisj_darklaf_platform_windows_JNIDecorations */

#ifndef _Included_com_github_weisj_darklaf_platform_windows_JNIDecorations
#define _Included_com_github_weisj_darklaf_platform_windows_JNIDecorations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_weisj_darklaf_platform_windows_JNIDecorations
 * Method:    updateValues
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_github_weisj_darklaf_platform_windows_JNIDecorations_updateValues
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_github_weisj_darklaf_platform_windows_JNIDecorations
 * Method:    setResizable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_github_weisj_darklaf_platform_windows_JNIDecorations_setResizable
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_github_weisj_darklaf_platform_windows_JNIDecorations
 * Method:    setBackground
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_github_weisj_darklaf_platform_windows_JNIDecorations_setBackground
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_github_weisj_darklaf_platform_windows_JNIDecorations
 * Method:    minimize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_weisj_darklaf_platform_windows_JNIDecorations_minimize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_weisj_darklaf_platform_windows_JNIDecorations
 * Method:    maximize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_weisj_darklaf_platform_windows_JNIDecorations_maximize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_weisj_darklaf_platform_windows_JNIDecorations
 * Method:    restore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_weisj_darklaf_platform_windows_JNIDecorations_restore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_weisj_darklaf_platform_windows_JNIDecorations
 * Method:    installDecorations
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_weisj_darklaf_platform_windows_JNIDecorations_installDecorations
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_weisj_darklaf_platform_windows_JNIDecorations
 * Method:    uninstallDecorations
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_weisj_darklaf_platform_windows_JNIDecorations_uninstallDecorations
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
